// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { JsonValue } from "./serde_json/JsonValue";

export type ApiError = { code: ErrorCode; details: JsonValue | null };
