// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Asset 分类;definition 的具体 schema 由 core 按 kind 解码。
 */
export type AssetKind =
  | "character"
  | "persona"
  | "world_book"
  | "open_ai_chat_preset"
  | "regex_script"
  | "pipeline"
  | "chat_history"
  | "media";
