// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";

/**
 * 对适配层暴露的 Asset 头视图。
 */
export type AssetHeadDto = {
  id: number;
  kind: AssetKind;
  name: string;
  head_revision: number;
  /**
   * 归属者;`None` 表示共享。
   */
  owner_id: number | null;
};
