// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioChunking =
  | { type: "auto" }
  | {
      type: "server_vad";
      threshold: number | null;
      prefix_padding_ms: number | null;
      silence_duration_ms: number | null;
    };
