// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioArtifact } from "./AudioArtifact";
import type { Transcription } from "./Transcription";
import type { Translation } from "./Translation";

export type AudioResponse =
  | ({ type: "speech" } & AudioArtifact)
  | ({ type: "transcription" } & Transcription)
  | ({ type: "translation" } & Translation);
