// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechRequest } from "./SpeechRequest";
import type { TranscriptionRequest } from "./TranscriptionRequest";
import type { TranslationRequest } from "./TranslationRequest";

export type AudioRequest =
  | ({ type: "speech" } & SpeechRequest)
  | ({ type: "transcribe" } & TranscriptionRequest)
  | ({ type: "translate" } & TranslationRequest);
