// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage";

export type AudioUsage =
  ({ type: "tokens" } & Usage) | { type: "duration"; seconds: number };
