// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对适配层暴露的渠道视图。
 */
export type ChannelDto = {
  id: number;
  name: string;
  base_url: string;
  enabled: boolean;
};
