// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterV1 } from "./CharacterV1";

export type CharacterDefinition = { version: "V1" } & CharacterV1;
