// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepthPrompt } from "./DepthPrompt";
import type { MediaRef } from "./MediaRef";
import type { RegexScriptRef } from "./RegexScriptRef";
import type { WorldBookRef } from "./WorldBookRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type CharacterV1 = {
  name: string;
  description: string;
  personality: string;
  scenario: string;
  creator_notes: string;
  /**
   * 主系统提示词覆盖(CCv2 `system_prompt`)。
   */
  system_prompt: string;
  /**
   * 历史后指令覆盖(CCv2 `post_history_instructions`)。
   */
  post_history_instructions: string;
  /**
   * 有序开场白:第一项对应 `first_mes`,其余对应 `alternate_greetings`。
   */
  greetings: Array<string>;
  /**
   * 示例对话(CCv2 `mes_example`)原文。
   */
  example_dialogue: string;
  tags: Array<string>;
  creator: string;
  character_version: string;
  /**
   * 角色专用的按深度提示词(ST `extensions.depth_prompt`)。
   */
  depth_prompt: DepthPrompt | null;
  world_books: Array<WorldBookRef>;
  regex_scripts: Array<RegexScriptRef>;
  avatar: MediaRef | null;
  /**
   * CCv2 extensions 与未识别字段的保真数据。
   */
  extra: { [key in string]: JsonValue };
};
