// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationTrigger } from "./GenerationTrigger";
import type { ModelId } from "./ModelId";
import type { SlotBinding } from "./SlotBinding";

/**
 * 发起一次聊天 run。
 */
export type ChatRunRequest = {
  pipeline_asset_id: number;
  bindings: Array<SlotBinding>;
  channel_id: number;
  model: ModelId;
  user_message: string | null;
  trigger: GenerationTrigger;
};
