// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { InputContent } from "./InputContent";
import type { ModelId } from "./ModelId";
import type { OutputItem } from "./OutputItem";
import type { ToolResult } from "./ToolResult";
import type { Usage } from "./Usage";

/**
 * 单条消息——内容寻址的可编辑单元(HashEdit 的锚点)。
 */
export type ChatMessage =
  | { role: "user"; content: Array<InputContent>; created_at_ms: number }
  | {
      role: "assistant";
      output: Array<OutputItem>;
      model: ModelId;
      finish: FinishReason;
      usage: Usage | null;
      created_at_ms: number;
    }
  | { role: "tool"; result: ToolResult; created_at_ms: number }
  | { role: "system"; text: string; created_at_ms: number };
