// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI 启动时需要的默认资产。
 */
export type ChatBootstrap = {
  pipeline_asset_id: number;
  preset_asset_id: number;
};
