// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";
import type { JsonValue } from "./serde_json/JsonValue";

export type ChatEvent =
  | { type: "frame"; event: string; data: JsonValue }
  | { type: "done" }
  | { type: "error"; error: ApiError };
