// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetHeadDto } from "./AssetHeadDto";
import type { ChatMessage } from "./ChatMessage";
import type { SessionBindings } from "./SessionBindings";

/**
 * 一段历史的视图:消息 + 当前 revision(用于 HashEdit 与并发)。
 */
export type ChatHistoryView = {
  head: AssetHeadDto;
  revision: number;
  title: string;
  bindings: SessionBindings;
  messages: Array<ChatMessage>;
};
