// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ForkOrigin } from "./ForkOrigin";
import type { SessionBindings } from "./SessionBindings";
import type { JsonValue } from "./serde_json/JsonValue";

export type ChatHistoryV1 = {
  title: string;
  messages: Array<ChatMessage>;
  /**
   * 会话默认绑定;可被单次 run 覆盖。
   */
  bindings: SessionBindings;
  /**
   * 分支来源:fork 自哪段历史的第几条消息之后。
   */
  forked_from: ForkOrigin | null;
  extra: { [key in string]: JsonValue };
};
