// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatHistoryV1 } from "./ChatHistoryV1";

export type ChatHistoryDefinition = { version: "V1" } & ChatHistoryV1;
