// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CitationSource =
  | { type: "url"; url: string }
  | { type: "file"; file_id: string }
  | { type: "document"; document_id: string };
