// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationSource } from "./CitationSource";

export type Citation = {
  start: number;
  end: number;
  source: CitationSource;
  title: string | null;
};
