// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { Instruction } from "./Instruction";
import type { ModelId } from "./ModelId";

export type CompactRequest = {
  model: ModelId;
  input: Array<InputItem>;
  instructions: Array<Instruction>;
  max_output_tokens: number | null;
};
