// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";

export type CompactionOutput = {
  id: OutputId;
  content: string | null;
  encrypted_content: string;
};
