// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputItem } from "./OutputItem";
import type { Usage } from "./Usage";

export type CompactResponse = {
  output: Array<OutputItem>;
  encrypted_content: string | null;
  usage: Usage | null;
};
