// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerEnvironment } from "./ComputerEnvironment";

export type ComputerUseTool = {
  environment: ComputerEnvironment;
  display_width: number;
  display_height: number;
};
