// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeSession } from "./RealtimeSession";

export type ConnectRealtimeRequest = { session: RealtimeSession };
