// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentKind =
  | "text"
  | "refusal"
  | "reasoning_text"
  | "tool_input"
  | "audio"
  | "transcript"
  | "image";
