// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ST 上下文组装辅助字段:包裹世界书/场景/性格的模板与固定提示语。
 */
export type ContextAssembly = {
  max_context_tokens: number | null;
  max_output_tokens: number | null;
  /**
   * 内容为空的提示词是否仍然发送。
   */
  send_if_empty: boolean;
  world_info_format: string;
  scenario_format: string;
  personality_format: string;
  new_chat_prompt: string;
  new_example_chat_prompt: string;
  continue_nudge_prompt: string;
  impersonation_prompt: string;
};
