// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentId } from "./ContentId";
import type { ContentKind } from "./ContentKind";

export type ContentStarted = {
  output_index: number;
  content_index: number;
  content_id: ContentId;
  kind: ContentKind;
};
