// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputItem } from "./OutputItem";

export type Conversation = {
  id: string;
  items: Array<OutputItem>;
  metadata: { [key in string]: string };
};
