// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { TokenCountInput } from "./TokenCountInput";

export type CountTokensRequest = { model: ModelId; input: TokenCountInput };
