// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";
import type { ModelId } from "./ModelId";

export type CreateVideoRequest = {
  model: ModelId;
  prompt: string;
  /**
   * 时长(秒)。
   */
  seconds: number | null;
  /**
   * `宽x高`,canonical OpenAI 形态;Gemini 渠道映射为宽高比 + 分辨率。
   */
  size: string | null;
  /**
   * 参考图;Gemini 渠道要求内联数据。
   */
  input_reference: MediaSource | null;
};
