// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";

export type CreateConversationRequest = {
  items: Array<InputItem>;
  metadata: { [key in string]: string };
};
