// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 凭证视图；不含 secret，避免泄露到前端。
 */
export type CredentialDto = {
  id: number;
  channel_id: number;
  label: string;
  weight: number;
  disabled: boolean;
  failure_count: number;
};
