// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrammarSyntax } from "./GrammarSyntax";

export type CustomToolInputFormat =
  | { type: "text" }
  | { type: "grammar"; syntax: GrammarSyntax; definition: string };
