// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomToolInputFormat } from "./CustomToolInputFormat";

export type CustomTool = {
  name: string;
  description: string | null;
  input_format: CustomToolInputFormat;
};
