// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { ToolCallId } from "./ToolCallId";

export type CustomToolCall = {
  id: OutputId;
  call_id: ToolCallId;
  name: string;
  input: string;
};
