// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionRole } from "./InjectionRole";

export type DepthPrompt = {
  prompt: string;
  depth: number;
  role: InjectionRole;
};
