// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioChunking } from "./AudioChunking";
import type { KnownSpeaker } from "./KnownSpeaker";

export type DiarizationConfig = {
  known_speakers: Array<KnownSpeaker>;
  chunking: AudioChunking | null;
};
