// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadVideoContentRequest = {
  /**
   * 取自 [`VideoJob::content_ref`]。
   */
  id: string;
};
