// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageInputFidelity } from "./ImageInputFidelity";
import type { ImageMode } from "./ImageMode";
import type { ImageOptions } from "./ImageOptions";
import type { MediaSource } from "./MediaSource";
import type { ModelId } from "./ModelId";

export type EditImageRequest = {
  model: ModelId;
  prompt: string;
  images: Array<MediaSource>;
  mask: MediaSource | null;
  count: number | null;
  input_fidelity: ImageInputFidelity | null;
  options: ImageOptions;
  mode: ImageMode;
};
