// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingInput } from "./EmbeddingInput";
import type { EmbeddingTask } from "./EmbeddingTask";
import type { ModelId } from "./ModelId";

export type EmbeddingRequest = {
  model: ModelId;
  input: EmbeddingInput;
  dimensions: number | null;
  task: EmbeddingTask | null;
};
