// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmbeddingTask =
  | "retrieval_query"
  | "retrieval_document"
  | "semantic_similarity"
  | "classification"
  | "clustering"
  | "question_answering"
  | "fact_verification"
  | "code_retrieval_query";
