// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmbeddingInput =
  | { type: "text"; value: string }
  | { type: "text_batch"; values: Array<string> }
  | { type: "tokens"; value: Array<number> }
  | { type: "token_batch"; values: Array<Array<number>> };
