// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingVector } from "./EmbeddingVector";
import type { ModelId } from "./ModelId";
import type { Usage } from "./Usage";

export type EmbeddingResponse = {
  model: ModelId | null;
  vectors: Array<EmbeddingVector>;
  usage: Usage | null;
};
