// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 注入位置;ST 以 0-7 编码,outlet 后置不建模。
 */
export type EntryPosition =
  | "before_character"
  | "after_character"
  | "top_author_note"
  | "bottom_author_note"
  | "at_depth"
  | "top_example_messages"
  | "bottom_example_messages";
