// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode =
  | "database"
  | "upstream_unavailable"
  | "invalid_data"
  | "invalid_route"
  | "channel_not_found"
  | "no_usable_credential"
  | "unsupported_route"
  | "unsupported_capability"
  | "upstream_rejected"
  | "asset_not_found"
  | "conflict"
  | "unauthorized"
  | "forbidden";
