// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { MediaSource } from "./MediaSource";

export type FileSource =
  | { type: "media"; source: MediaSource }
  | { type: "id"; id: FileId }
  | { type: "text"; filename: string | null; text: string };
