// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchRanking } from "./FileSearchRanking";
import type { JsonValue } from "./serde_json/JsonValue";

export type FileSearchTool = {
  vector_store_ids: Array<string>;
  max_results: number | null;
  ranking: FileSearchRanking | null;
  filters: JsonValue | null;
};
