// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatHistoryRef } from "./ChatHistoryRef";

export type ForkOrigin = {
  source: ChatHistoryRef;
  source_revision: number;
  /**
   * 保留到源历史的第几条消息(独占上界)。
   */
  message_count: number;
};
