// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { GenerationId } from "./GenerationId";
import type { ModelId } from "./ModelId";
import type { OutputItem } from "./OutputItem";
import type { Usage } from "./Usage";

export type GenerateResponse = {
  id: GenerationId;
  model: ModelId;
  output: Array<OutputItem>;
  finish: FinishReason;
  usage: Usage;
};
