// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerateMode } from "./GenerateMode";
import type { GenerationLimits } from "./GenerationLimits";
import type { InputItem } from "./InputItem";
import type { Instruction } from "./Instruction";
import type { ModelId } from "./ModelId";
import type { OutputConstraint } from "./OutputConstraint";
import type { OutputModality } from "./OutputModality";
import type { ProtocolOptions } from "./ProtocolOptions";
import type { ReasoningOptions } from "./ReasoningOptions";
import type { SamplingOptions } from "./SamplingOptions";
import type { ToolChoice } from "./ToolChoice";
import type { ToolDefinition } from "./ToolDefinition";

export type GenerateRequest = {
  model: ModelId;
  input: Array<InputItem>;
  instructions: Array<Instruction>;
  tools: Array<ToolDefinition>;
  tool_choice: ToolChoice;
  output: OutputConstraint;
  sampling: SamplingOptions;
  reasoning: ReasoningOptions | null;
  protocol_options: Array<ProtocolOptions>;
  limits: GenerationLimits;
  modalities: Array<OutputModality>;
  mode: GenerateMode;
};
