// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageMode } from "./ImageMode";
import type { ImageOptions } from "./ImageOptions";
import type { ModelId } from "./ModelId";

export type GenerateImageRequest = {
  model: ModelId;
  prompt: string;
  count: number | null;
  options: ImageOptions;
  mode: ImageMode;
};
