// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentFinished } from "./ContentFinished";
import type { ContentStarted } from "./ContentStarted";
import type { GenerateDelta } from "./GenerateDelta";
import type { GenerationFailure } from "./GenerationFailure";
import type { GenerationFinished } from "./GenerationFinished";
import type { GenerationStarted } from "./GenerationStarted";
import type { OutputFinished } from "./OutputFinished";
import type { OutputStarted } from "./OutputStarted";
import type { Usage } from "./Usage";

export type GenerateEvent =
  | { type: "started"; data: GenerationStarted }
  | { type: "output_started"; data: OutputStarted }
  | { type: "content_started"; data: ContentStarted }
  | { type: "delta"; data: GenerateDelta }
  | { type: "content_finished"; data: ContentFinished }
  | { type: "output_finished"; data: OutputFinished }
  | { type: "usage_updated"; data: Usage }
  | { type: "finished"; data: GenerationFinished }
  | { type: "failed"; data: GenerationFailure };
