// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationFailure } from "./OperationFailure";
import type { Usage } from "./Usage";

export type GenerationFailure = {
  error: OperationFailure;
  usage: Usage | null;
};
