// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationId } from "./GenerationId";
import type { ModelId } from "./ModelId";

export type GenerationStarted = { id: GenerationId; model: ModelId };
