// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 生成类型;run 的 `trigger` 参数取值同源。
 */
export type GenerationTrigger =
  "normal" | "continue" | "impersonate" | "swipe" | "regenerate" | "quiet";
