// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryDelta } from "./BinaryDelta";
import type { CitationDelta } from "./CitationDelta";
import type { CompactionDelta } from "./CompactionDelta";
import type { ContentTextDelta } from "./ContentTextDelta";
import type { ImageDelta } from "./ImageDelta";
import type { JsonFragmentDelta } from "./JsonFragmentDelta";
import type { OutputTextDelta } from "./OutputTextDelta";
import type { ToolExecutionDelta } from "./ToolExecutionDelta";

export type GenerateDelta =
  | { type: "text"; data: ContentTextDelta }
  | { type: "refusal"; data: ContentTextDelta }
  | { type: "reasoning_summary"; data: ContentTextDelta }
  | { type: "reasoning_text"; data: ContentTextDelta }
  | { type: "compaction"; data: CompactionDelta }
  | { type: "function_arguments"; data: JsonFragmentDelta }
  | { type: "custom_tool_input"; data: OutputTextDelta }
  | { type: "audio"; data: BinaryDelta }
  | { type: "transcript"; data: ContentTextDelta }
  | { type: "image"; data: ImageDelta }
  | { type: "citation"; data: CitationDelta }
  | { type: "tool_execution"; data: ToolExecutionDelta };
