// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { Instruction } from "./Instruction";
import type { ToolDefinition } from "./ToolDefinition";

export type GenerationTokenInput = {
  input: Array<InputItem>;
  instructions: Array<Instruction>;
  tools: Array<ToolDefinition>;
};
