// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerationLimits = {
  max_output_tokens: number | null;
  max_tool_calls: number | null;
};
