// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkHash } from "./ChunkHash";
import type { HashEditOp } from "./HashEditOp";

export type HashEdit = { target_hash: ChunkHash; op: HashEditOp };
