// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type HashEditOp =
  | { op: "replace"; new_content: JsonValue }
  | { op: "delete" }
  | { op: "insert_after"; new_content: JsonValue };
