// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageBackground } from "./ImageBackground";
import type { ImageFormat } from "./ImageFormat";
import type { ImageModeration } from "./ImageModeration";
import type { ImageQuality } from "./ImageQuality";

export type ImageOptions = {
  width: number | null;
  height: number | null;
  quality: ImageQuality | null;
  background: ImageBackground | null;
  output_format: ImageFormat | null;
  compression: number | null;
  moderation: ImageModeration | null;
  partial_images: number | null;
};
