// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageGenerationTool = {
  size: string | null;
  quality: string | null;
  background: string | null;
  output_format: string | null;
};
