// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageArtifact } from "./ImageArtifact";

export type ImagePreview = {
  index: number;
  sequence: number;
  image: ImageArtifact;
};
