// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";
import type { OutputId } from "./OutputId";

export type ImageArtifact = {
  id: OutputId;
  source: MediaSource;
  revised_prompt: string | null;
};
