// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditImageRequest } from "./EditImageRequest";
import type { GenerateImageRequest } from "./GenerateImageRequest";

export type ImageRequest =
  | ({ type: "generate" } & GenerateImageRequest)
  | ({ type: "edit" } & EditImageRequest);
