// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageDelta = {
  output_index: number;
  content_index: number;
  encoded: string;
  sequence: number;
};
