// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetHeadDto } from "./AssetHeadDto";

/**
 * 一次角色卡导入的结果。
 */
export type ImportedCharacter = {
  character: AssetHeadDto;
  world_book: AssetHeadDto | null;
};
