// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 注入消息的角色;ST 以 0/1/2 编码,观复用具名值。
 */
export type InjectionRole = "system" | "user" | "assistant";
