// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpApprovalResponse } from "./McpApprovalResponse";
import type { Message } from "./Message";
import type { ReasoningInput } from "./ReasoningInput";
import type { ToolResult } from "./ToolResult";

export type InputItem =
  | { type: "message"; message: Message }
  | { type: "tool_result"; result: ToolResult }
  | { type: "mcp_approval"; approval: McpApprovalResponse }
  | { type: "reasoning"; reasoning: ReasoningInput };
