// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";

export type InputSlot = {
  name: string;
  kind: AssetKind;
  /**
   * 允许绑定多个 Asset(如 world_books[])。
   */
  many: boolean;
  required: boolean;
};
