// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputContent } from "./InputContent";
import type { InstructionRole } from "./InstructionRole";

export type Instruction = {
  role: InstructionRole;
  content: Array<InputContent>;
};
