// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKeyDto } from "./OperationKeyDto";
import type { JsonValue } from "./serde_json/JsonValue";

export type LlmRequestDto = {
  channel_id: number;
  operation: OperationKeyDto;
  model: string;
  stream: boolean;
  body: JsonValue | null;
};
