// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Responses 的 mcp_approval_request：模型请求批准调用某个 MCP 工具，
 * 调用方以 [`super::McpApprovalResponse`] 回复。
 */
export type McpApprovalRequest = {
  id: OutputId;
  server_label: string;
  name: string;
  arguments: JsonValue;
};
