// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对 [`super::McpApprovalRequest`] 的答复。
 */
export type McpApprovalResponse = {
  approval_request_id: string;
  approve: boolean;
};
