// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpApproval } from "./McpApproval";

export type McpTool = {
  server_label: string;
  server_url: string;
  allowed_tools: Array<string>;
  approval: McpApproval;
};
