// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaV1 } from "./MediaV1";

export type MediaDefinition = { version: "V1" } & MediaV1;
