// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkHash } from "./ChunkHash";
import type { JsonValue } from "./serde_json/JsonValue";

export type MediaV1 = {
  /**
   * 内容哈希,同时是 AssetStore 的 storage key。
   */
  hash: ChunkHash;
  mime_type: string;
  size: number;
  /**
   * 原始文件名(导入保真用)。
   */
  filename: string | null;
  extra: { [key in string]: JsonValue };
};
