// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { MediaType } from "./MediaType";

export type MediaSource =
  | { type: "url"; url: string }
  | { type: "data"; media_type: MediaType; bytes: number[] }
  | { type: "file"; id: FileId };
