// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetHeadDto } from "./AssetHeadDto";

/**
 * 一次媒体操作的产物。
 */
export type MediaResult = {
  /**
   * 已落库的 Media Asset。
   */
  assets: Array<AssetHeadDto>;
  /**
   * 上游只给了 URL 的产物;不落库,由 UI 外链或用户另存。
   */
  urls: Array<string>;
};
