// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputContent } from "./InputContent";
import type { MessageRole } from "./MessageRole";

export type Message = { role: MessageRole; content: Array<InputContent> };
