// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";
import type { ModelPage } from "./ModelPage";

export type ModelResponse =
  ({ type: "list" } & ModelPage) | ({ type: "one" } & Model);
