// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCapability } from "./ModelCapability";
import type { ModelId } from "./ModelId";

export type Model = {
  id: ModelId;
  display_name: string | null;
  description: string | null;
  created_at: number | null;
  capabilities: Array<ModelCapability>;
  context_limit: number | null;
  output_limit: number | null;
};
