// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetModelRequest } from "./GetModelRequest";
import type { ListModelsRequest } from "./ListModelsRequest";

export type ModelRequest =
  ({ type: "list" } & ListModelsRequest) | ({ type: "get" } & GetModelRequest);
