// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelCapability =
  | "generate_text"
  | "generate_image"
  | "image_input"
  | "audio_input"
  | "audio_output"
  | "embeddings"
  | "tools"
  | "reasoning";
