// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewCredential = {
  channel_id: number;
  label: string;
  secret: string;
  weight: number;
};
