// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

export type Node = { id: string } & (
  | {
      kind: "context_build";
      /**
       * 参与组装的输入槽位名。
       */
      slots: Array<string>;
    }
  | {
      kind: "generate";
      /**
       * 模型与渠道由 run 参数提供,不固定在可分享 pipeline 里。
       */
      model_param: string;
      channel_param: string;
      stream: boolean;
    }
  | { kind: "text_transform"; regex_slots: Array<string> }
  | {
      kind: "media_generate";
      model_param: string;
      channel_param: string;
      media: MediaKind;
    }
  | {
      kind: "map";
      /**
       * 被遍历的输入槽位名。
       */
      slot: string;
      /**
       * 对每一项执行的节点 id。
       */
      node: string;
    }
);
