// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAiChatPresetV1 } from "./OpenAiChatPresetV1";

export type OpenAiChatPresetDefinition = { version: "V1" } & OpenAiChatPresetV1;
