// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAssembly } from "./ContextAssembly";
import type { PromptItem } from "./PromptItem";
import type { PromptOrderProfile } from "./PromptOrderProfile";
import type { ReasoningOptions } from "./ReasoningOptions";
import type { RegexScriptRef } from "./RegexScriptRef";
import type { SamplingOptions } from "./SamplingOptions";
import type { JsonValue } from "./serde_json/JsonValue";

export type OpenAiChatPresetV1 = {
  name: string;
  /**
   * 全部提示词项,按 identifier 被 order profile 引用。
   */
  prompts: Array<PromptItem>;
  /**
   * prompt-order profile;ST 用虚拟 character_id 区分,观复用具名 profile。
   */
  prompt_orders: Array<PromptOrderProfile>;
  sampling: SamplingOptions;
  reasoning: ReasoningOptions | null;
  context: ContextAssembly;
  regex_scripts: Array<RegexScriptRef>;
  extra: { [key in string]: JsonValue };
};
