// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerateEvent } from "./GenerateEvent";
import type { ImageEvent } from "./ImageEvent";
import type { SpeechEvent } from "./SpeechEvent";
import type { TranscriptionEvent } from "./TranscriptionEvent";

export type OperationEvent =
  | { operation: "generate"; event: GenerateEvent }
  | { operation: "image"; event: ImageEvent }
  | { operation: "speech"; event: SpeechEvent }
  | { operation: "transcription"; event: TranscriptionEvent };
