// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioRequest } from "./AudioRequest";
import type { CountTokensRequest } from "./CountTokensRequest";
import type { EmbeddingRequest } from "./EmbeddingRequest";
import type { GenerateRequest } from "./GenerateRequest";
import type { ImageRequest } from "./ImageRequest";
import type { ModelRequest } from "./ModelRequest";
import type { PlatformRequest } from "./PlatformRequest";
import type { SearchRequest } from "./SearchRequest";

export type OperationRequest =
  | { operation: "models"; request: ModelRequest }
  | { operation: "count_tokens"; request: CountTokensRequest }
  | { operation: "generate"; request: GenerateRequest }
  | { operation: "embeddings"; request: EmbeddingRequest }
  | { operation: "images"; request: ImageRequest }
  | { operation: "audio"; request: AudioRequest }
  | { operation: "search"; request: SearchRequest }
  | { operation: "platform"; request: PlatformRequest };
