// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type OperationFailure = {
  code: string;
  message: string;
  retryable: boolean;
  details: { [key in string]: JsonValue };
};
