// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioResponse } from "./AudioResponse";
import type { CountTokensResponse } from "./CountTokensResponse";
import type { EmbeddingResponse } from "./EmbeddingResponse";
import type { GenerateResponse } from "./GenerateResponse";
import type { ImageResponse } from "./ImageResponse";
import type { ModelResponse } from "./ModelResponse";
import type { PlatformResponse } from "./PlatformResponse";
import type { SearchResponse } from "./SearchResponse";
import type { VideoResponse } from "./VideoResponse";

export type OperationResponse =
  | { operation: "models"; response: ModelResponse }
  | { operation: "count_tokens"; response: CountTokensResponse }
  | { operation: "generate"; response: GenerateResponse }
  | { operation: "embeddings"; response: EmbeddingResponse }
  | { operation: "images"; response: ImageResponse }
  | { operation: "audio"; response: AudioResponse }
  | { operation: "search"; response: SearchResponse }
  | { operation: "video"; response: VideoResponse }
  | { operation: "platform"; response: PlatformResponse };
