// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputContent } from "./OutputContent";
import type { OutputId } from "./OutputId";

export type OutputMessage = { id: OutputId; content: Array<OutputContent> };
