// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonSchema } from "./JsonSchema";

export type OutputConstraint =
  | { type: "text" }
  | { type: "json_object" }
  | { type: "json_schema"; name: string; schema: JsonSchema; strict: boolean };
