// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioArtifact } from "./AudioArtifact";
import type { CompactionOutput } from "./CompactionOutput";
import type { ImageArtifact } from "./ImageArtifact";
import type { McpApprovalRequest } from "./McpApprovalRequest";
import type { OutputMessage } from "./OutputMessage";
import type { ReasoningOutput } from "./ReasoningOutput";
import type { ToolCall } from "./ToolCall";
import type { ToolExecution } from "./ToolExecution";

export type OutputItem =
  | { type: "message"; item: OutputMessage }
  | { type: "reasoning"; item: ReasoningOutput }
  | { type: "compaction"; item: CompactionOutput }
  | { type: "tool_call"; item: ToolCall }
  | { type: "tool_execution"; item: ToolExecution }
  | { type: "mcp_approval_request"; item: McpApprovalRequest }
  | { type: "image"; item: ImageArtifact }
  | { type: "audio"; item: AudioArtifact };
