// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputKind =
  | "message"
  | "reasoning"
  | "compaction"
  | "tool_call"
  | "tool_execution"
  | "mcp_approval_request"
  | "audio";
