// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { OutputKind } from "./OutputKind";

export type OutputStarted = {
  output_index: number;
  output_id: OutputId;
  kind: OutputKind;
};
