// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 输出操作:新建 / 追加 / 以 HashEdit 锚定的修订。
 */
export type OutputOp = "create" | "append" | "hash_edit";
