// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputOp } from "./OutputOp";

export type OutputDecl = {
  /**
   * 目标输入槽位名(写回该槽绑定的 Asset)。
   */
  slot: string;
  op: OutputOp;
  /**
   * `node.port`。
   */
  from: string;
};
