// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaV1 } from "./PersonaV1";

export type PersonaDefinition = { version: "V1" } & PersonaV1;
