// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionRole } from "./InjectionRole";
import type { MediaRef } from "./MediaRef";
import type { PersonaPosition } from "./PersonaPosition";
import type { WorldBookRef } from "./WorldBookRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type PersonaV1 = {
  name: string;
  description: string;
  position: PersonaPosition;
  /**
   * `position = at_depth` 时的注入深度与角色。
   */
  depth: number | null;
  role: InjectionRole | null;
  avatar: MediaRef | null;
  world_books: Array<WorldBookRef>;
  extra: { [key in string]: JsonValue };
};
