// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * persona 描述的注入位置;ST 的已废弃 `after_char` 不建模,导入时归一。
 */
export type PersonaPosition =
  "in_prompt" | "top_author_note" | "bottom_author_note" | "at_depth" | "none";
