// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { InputSlot } from "./InputSlot";
import type { Node } from "./Node";
import type { OutputDecl } from "./OutputDecl";
import type { ParamSpec } from "./ParamSpec";
import type { JsonValue } from "./serde_json/JsonValue";

export type PipelineV1 = {
  name: string;
  /**
   * 槽位签名:run 发起时按 kind 校验绑定并钉住 revision。
   */
  inputs: Array<InputSlot>;
  /**
   * 非 Asset 运行参数(user_message、trigger…)。
   */
  params: Array<ParamSpec>;
  nodes: Array<Node>;
  edges: Array<Edge>;
  /**
   * 对 Asset 的写入声明;run 结束原子提交。
   */
  outputs: Array<OutputDecl>;
  extra: { [key in string]: JsonValue };
};
