// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";
import type { OperationEvent } from "./OperationEvent";
import type { ResolvedSlot } from "./ResolvedSlot";

/**
 * run 期间流向 UI 的事件;只有已建模的语义,不透传协议 JSON。
 */
export type PipelineEvent =
  | { type: "started"; run_id: number }
  | { type: "progress"; event: OperationEvent }
  | { type: "committed"; run_id: number; history: ResolvedSlot }
  | { type: "failed"; run_id: number | null; error: ApiError };
