// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineV1 } from "./PipelineV1";

export type PipelineDefinition = { version: "V1" } & PipelineV1;
