// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactRequest } from "./CompactRequest";
import type { ConnectRealtimeRequest } from "./ConnectRealtimeRequest";
import type { CreateConversationRequest } from "./CreateConversationRequest";
import type { CreateRealtimeCallRequest } from "./CreateRealtimeCallRequest";

export type PlatformRequest =
  | ({ type: "compact" } & CompactRequest)
  | ({ type: "create_conversation" } & CreateConversationRequest)
  | ({ type: "create_realtime_call" } & CreateRealtimeCallRequest)
  | ({ type: "connect_realtime" } & ConnectRealtimeRequest);
