// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactResponse } from "./CompactResponse";
import type { Conversation } from "./Conversation";
import type { RealtimeCall } from "./RealtimeCall";

export type PlatformResponse =
  | ({ type: "compact" } & CompactResponse)
  | ({ type: "conversation" } & Conversation)
  | ({ type: "realtime_call" } & RealtimeCall);
