// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationTrigger } from "./GenerationTrigger";

/**
 * 提示词的注入方式:相对编排,或按聊天深度注入。
 */
export type PromptInjection =
  | { type: "relative" }
  | {
      type: "at_depth";
      depth: number;
      /**
       * 同深度下的次序。
       */
      order: number;
      /**
       * 限定生成类型;空表示不限。
       */
      triggers: Array<GenerationTrigger>;
    };
