// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionRole } from "./InjectionRole";
import type { PromptInjection } from "./PromptInjection";
import type { PromptMarker } from "./PromptMarker";
import type { JsonValue } from "./serde_json/JsonValue";

export type PromptItem = {
  /**
   * 稳定标识;排序和覆盖按它关联。
   */
  identifier: string;
  name: string;
  role: InjectionRole;
  /**
   * marker 项可没有正文。
   */
  content: string;
  /**
   * 动态槽位(角色描述、历史、世界书等)而非静态文本。
   */
  marker: PromptMarker | null;
  injection: PromptInjection;
  /**
   * 禁止角色卡覆盖此提示词。
   */
  forbid_overrides: boolean;
  extra: { [key in string]: JsonValue };
};
