// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 内置动态槽位;未知 marker 名保留在 `PromptItem::extra`。
 */
export type PromptMarker =
  | "world_info_before"
  | "world_info_after"
  | "character_description"
  | "character_personality"
  | "scenario"
  | "persona_description"
  | "dialogue_examples"
  | "chat_history";
