// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationProtocol } from "./GenerationProtocol";
import type { JsonMergePatch } from "./JsonMergePatch";

export type ProtocolOptions = {
  kind: GenerationProtocol;
  patch: JsonMergePatch;
};
