// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKeyDto } from "./OperationKeyDto";
import type { RoutingImplementation } from "./RoutingImplementation";

export type PutRoutingRule = {
  channel_id: number;
  source: OperationKeyDto;
  implementation: RoutingImplementation;
  sort_order: number;
  enabled: boolean;
};
