// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealtimeTranscription = {
  model: string | null;
  language: string | null;
  prompt: string | null;
};
