// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealtimeAudioFormat =
  | { type: "pcm16"; rate: number | null }
  | { type: "g711_ulaw" }
  | { type: "g711_alaw" };
