// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCall } from "./FunctionCall";
import type { OperationFailure } from "./OperationFailure";
import type { RealtimeFinish } from "./RealtimeFinish";
import type { Usage } from "./Usage";

/**
 * 会话 → 调用方 的语义事件。
 *
 * 未建模的服务端事件(item 生命周期细节、限流通报等)被有意忽略,
 * 会话不因协议演进中断;这是 realtime 与 HTTP 流式解码的显式差异。
 */
export type RealtimeServerEvent =
  | { type: "session_created" }
  | { type: "session_updated" }
  | { type: "input_speech_started"; item_id: string }
  | { type: "input_speech_stopped"; item_id: string }
  | { type: "input_audio_committed"; item_id: string }
  | { type: "input_transcript_delta"; item_id: string; delta: string }
  | { type: "input_transcript_completed"; item_id: string; transcript: string }
  | {
      type: "input_transcript_failed";
      item_id: string;
      error: OperationFailure;
    }
  | { type: "response_started"; response_id: string }
  | { type: "audio_delta"; item_id: string; delta: string }
  | { type: "audio_done"; item_id: string }
  | { type: "output_transcript_delta"; item_id: string; delta: string }
  | { type: "output_transcript_done"; item_id: string; transcript: string }
  | { type: "text_delta"; item_id: string; delta: string }
  | { type: "text_done"; item_id: string; text: string }
  | { type: "tool_call"; call: FunctionCall }
  | {
      type: "response_finished";
      response_id: string;
      status: RealtimeFinish;
      usage: Usage | null;
    }
  | { type: "error"; error: OperationFailure };
