// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instruction } from "./Instruction";
import type { ModelId } from "./ModelId";
import type { NoiseReductionMode } from "./NoiseReductionMode";
import type { RealtimeAudioFormat } from "./RealtimeAudioFormat";
import type { RealtimeModality } from "./RealtimeModality";
import type { RealtimeTranscription } from "./RealtimeTranscription";
import type { ToolChoice } from "./ToolChoice";
import type { ToolDefinition } from "./ToolDefinition";
import type { TurnDetection } from "./TurnDetection";

export type RealtimeSession = {
  model: ModelId;
  instructions: Array<Instruction>;
  modalities: Array<RealtimeModality>;
  voice: string | null;
  speed: number | null;
  input_audio_format: RealtimeAudioFormat | null;
  output_audio_format: RealtimeAudioFormat | null;
  input_transcription: RealtimeTranscription | null;
  noise_reduction: NoiseReductionMode | null;
  turn_detection: TurnDetection | null;
  tools: Array<ToolDefinition>;
  tool_choice: ToolChoice;
  max_output_tokens: number | null;
};
