// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { RealtimeSession } from "./RealtimeSession";

/**
 * 调用方 → 会话 的语义事件。
 */
export type RealtimeClientEvent =
  | { type: "update_session"; session: RealtimeSession }
  | { type: "append_audio"; audio: string }
  | { type: "commit_audio" }
  | { type: "clear_audio" }
  | { type: "create_item"; item: InputItem }
  | { type: "truncate_playback"; item_id: string; audio_end_ms: number }
  | { type: "create_response" }
  | { type: "cancel_response" };
