// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";
import type { RealtimeServerEvent } from "./RealtimeServerEvent";

/**
 * 下行帧:上游语义事件,或本端错误。
 */
export type RealtimeDownstream =
  | { type: "ready" }
  | { type: "event"; event: RealtimeServerEvent }
  | { type: "error"; error: ApiError };
