// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerateRequest } from "./GenerateRequest";
import type { Instruction } from "./Instruction";
import type { ModelId } from "./ModelId";
import type { RealtimeModality } from "./RealtimeModality";
import type { TurnDetection } from "./TurnDetection";

export type RealtimeSession = {
  model: ModelId;
  instructions: Array<Instruction>;
  modalities: Array<RealtimeModality>;
  voice: string | null;
  input_audio_format: string | null;
  output_audio_format: string | null;
  turn_detection: TurnDetection | null;
  generation: GenerateRequest | null;
};
