// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealtimeCall = {
  /**
   * 来自 `Location` 响应头的 call id;上游未返回时为 None。
   */
  id: string | null;
  answer_sdp: string;
};
