// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningSummary } from "./ReasoningSummary";

export type ReasoningOptions = {
  effort: ReasoningEffort | null;
  budget_tokens: number | null;
  summary: ReasoningSummary | null;
};
