// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";

export type ReasoningOutput = {
  id: OutputId;
  summary: Array<string>;
  encrypted_content: string | null;
  signature: string | null;
};
