// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReasoningContinuation =
  | { type: "open_ai_encrypted"; content: string }
  | { type: "claude_signature"; signature: string }
  | { type: "claude_redacted"; data: string }
  | { type: "gemini_thought_signature"; signature: string };
