// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningContinuation } from "./ReasoningContinuation";

export type ReasoningPart =
  | { type: "summary"; text: string }
  | { type: "text"; text: string; continuation: ReasoningContinuation | null }
  | { type: "opaque"; continuation: ReasoningContinuation };
