// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegexScriptV1 } from "./RegexScriptV1";

export type RegexScriptDefinition = { version: "V1" } & RegexScriptV1;
