// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 生效阶段;ST 的已废弃 `MD_DISPLAY`/`sendAs` 在导入时归一。
 */
export type RegexPlacement =
  "user_input" | "ai_output" | "slash_command" | "world_info" | "reasoning";
