// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroSubstitution } from "./MacroSubstitution";
import type { RegexPlacement } from "./RegexPlacement";
import type { JsonValue } from "./serde_json/JsonValue";

export type RegexScriptV1 = {
  name: string;
  /**
   * JS 风格 `/pattern/flags` 原文;编译在执行侧完成。
   */
  find_regex: string;
  /**
   * 支持 `{{match}}`、`$1`、`$<name>`。
   */
  replace_string: string;
  /**
   * 写入 replacement 前从捕获内容移除的字符串。
   */
  trim_strings: Array<string>;
  placements: Array<RegexPlacement>;
  /**
   * 只影响展示 / 只影响发送给模型的内容。
   */
  display_only: boolean;
  prompt_only: boolean;
  run_on_edit: boolean;
  substitute_macros: MacroSubstitution;
  /**
   * 只处理指定聊天深度范围。
   */
  min_depth: number | null;
  max_depth: number | null;
  extra: { [key in string]: JsonValue };
};
