// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RerankResult } from "./RerankResult";
import type { Usage } from "./Usage";

export type RerankResponse = {
  results: Array<RerankResult>;
  usage: Usage | null;
};
