// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { RerankDocument } from "./RerankDocument";

export type RerankRequest = {
  model: ModelId;
  query: string;
  documents: Array<RerankDocument>;
  top_n: number | null;
  return_documents: boolean;
};
