// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RerankDocument } from "./RerankDocument";

export type RerankResult = {
  index: number;
  relevance_score: number;
  document: RerankDocument | null;
};
