// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 解析后的槽位:revision 已钉住。
 */
export type ResolvedSlot = { slot: string; asset_id: number; revision: number };
