// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetrieveVideoRequest = {
  /**
   * 任务 id(OpenAI:video id;Gemini:操作资源名)。
   */
  id: string;
};
