// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKeyDto } from "./OperationKeyDto";

export type RoutingImplementation =
  | { type: "passthrough" }
  | { type: "transform_to"; target: OperationKeyDto }
  | { type: "local" }
  | { type: "unsupported" };
