// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutingKind =
  | "open_ai_responses"
  | "open_ai_responses_websocket"
  | "open_ai_chat_completions"
  | "claude_messages"
  | "gemini_generate_content"
  | "open_ai"
  | "claude"
  | "gemini";
