// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutingOperation =
  | "list_models"
  | "get_model"
  | "count_tokens"
  | "generate_content"
  | "stream_generate_content"
  | "create_image"
  | "edit_image"
  | "web_search"
  | "rerank"
  | "create_embedding"
  | "create_speech"
  | "create_transcription"
  | "create_translation"
  | "compact_content"
  | "create_conversation"
  | "create_realtime_call"
  | "connect_realtime";
