// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次 run 的生命周期状态。
 */
export type RunStatus =
  "pending" | "running" | "succeeded" | "failed" | "cancelled";
