// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SamplingOptions = {
  temperature: number | null;
  top_p: number | null;
  top_k: number | null;
  seed: number | null;
  stop: Array<string>;
};
