// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RerankRequest } from "./RerankRequest";
import type { WebSearchRequest } from "./WebSearchRequest";

export type SearchRequest =
  ({ type: "web" } & WebSearchRequest) | ({ type: "rerank" } & RerankRequest);
