// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RerankResponse } from "./RerankResponse";
import type { WebSearchResponse } from "./WebSearchResponse";

export type SearchResponse =
  ({ type: "web" } & WebSearchResponse) | ({ type: "rerank" } & RerankResponse);
