// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 次关键词的组合逻辑;ST 以 0-3 编码。
 */
export type SelectiveLogic = "and_any" | "not_all" | "not_any" | "and_all";
