// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationRequest } from "./OperationRequest";

export type SemanticLlmRequest = {
  channel_id: number;
  request: OperationRequest;
};
