// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";
import type { OperationEvent } from "./OperationEvent";

export type SemanticStreamMessage =
  { type: "event"; event: OperationEvent } | { type: "error"; error: ApiError };
