// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话视图;`id` 是令牌的哈希,不是令牌本身。
 */
export type SessionSummary = {
  id: string;
  created_at_ms: number;
  expires_at_ms: number;
  /**
   * 是否为发起本次请求的会话。
   */
  current: boolean;
};
