// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserDto } from "./UserDto";

/**
 * 登录成功的返回;`token` 只在此刻出现一次。
 */
export type SessionDto = { token: string; user: UserDto };
