// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterRef } from "./CharacterRef";
import type { ModelId } from "./ModelId";
import type { PersonaRef } from "./PersonaRef";
import type { PipelineRef } from "./PipelineRef";
import type { PresetRef } from "./PresetRef";

export type SessionBindings = {
  character: CharacterRef | null;
  persona: PersonaRef | null;
  preset: PresetRef | null;
  pipeline: PipelineRef | null;
  channel_id: number | null;
  model: ModelId | null;
};
