// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发起 run 时对一个槽位的绑定。
 */
export type SlotBinding = { slot: string; asset_ids: Array<number> };
