// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationFailure } from "./OperationFailure";

export type SpeechEvent =
  | { type: "started"; media_type: string }
  | { type: "audio_delta"; bytes: number[] }
  | { type: "finished" }
  | ({ type: "failed" } & OperationFailure);
