// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { ModelId } from "./ModelId";
import type { SpeechMode } from "./SpeechMode";
import type { Voice } from "./Voice";

export type SpeechRequest = {
  model: ModelId;
  input: string;
  voice: Voice;
  instructions: string | null;
  format: AudioFormat;
  speed: number | null;
  mode: SpeechMode;
};
