// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { ToolCallId } from "./ToolCallId";
import type { JsonValue } from "./serde_json/JsonValue";

export type TextEditorCall = {
  id: OutputId;
  call_id: ToolCallId;
  input: JsonValue;
};
