// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationTokenInput } from "./GenerationTokenInput";

export type TokenCountInput =
  | { type: "text"; values: Array<string> }
  | ({ type: "generation" } & GenerationTokenInput);
