// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { ToolCallId } from "./ToolCallId";
import type { ToolExecutionState } from "./ToolExecutionState";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 服务端执行的托管工具（web_search / file_search / code_interpreter /
 * image_generation / mcp 等）的调用与结果，调用方无需回传输出。
 */
export type ToolExecution = {
  id: OutputId;
  call_id: ToolCallId;
  state: ToolExecutionState;
  output: JsonValue | null;
  error: string | null;
};
