// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultContent } from "./ToolResultContent";

export type ToolOutcome =
  | { type: "success"; content: Array<ToolResultContent> }
  | { type: "error"; code: string | null; message: string };
