// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolResultKind =
  | "function"
  | "custom"
  | "computer_use"
  | "code_execution"
  | "shell"
  | "text_editor"
  | "memory"
  | "tool_search";
