// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllowedToolMode } from "./AllowedToolMode";

export type ToolChoice =
  | { type: "auto" }
  | { type: "none" }
  | { type: "required" }
  | { type: "tool"; name: string }
  | { type: "allowed"; names: Array<string>; mode: AllowedToolMode };
