// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeExecutionCall } from "./CodeExecutionCall";
import type { ComputerActionCall } from "./ComputerActionCall";
import type { CustomToolCall } from "./CustomToolCall";
import type { FunctionCall } from "./FunctionCall";
import type { HostedToolCall } from "./HostedToolCall";
import type { ImageGenerationCall } from "./ImageGenerationCall";
import type { McpCall } from "./McpCall";
import type { MemoryCall } from "./MemoryCall";
import type { ShellCall } from "./ShellCall";
import type { TextEditorCall } from "./TextEditorCall";
import type { ToolSearchCall } from "./ToolSearchCall";

export type ToolCall =
  | ({ type: "function" } & FunctionCall)
  | ({ type: "custom" } & CustomToolCall)
  | ({ type: "web_search" } & HostedToolCall)
  | ({ type: "web_fetch" } & HostedToolCall)
  | ({ type: "file_search" } & HostedToolCall)
  | ({ type: "computer_use" } & ComputerActionCall)
  | ({ type: "code_execution" } & CodeExecutionCall)
  | ({ type: "shell" } & ShellCall)
  | ({ type: "text_editor" } & TextEditorCall)
  | ({ type: "image_generation" } & ImageGenerationCall)
  | ({ type: "mcp" } & McpCall)
  | ({ type: "memory" } & MemoryCall)
  | ({ type: "tool_search" } & ToolSearchCall);
