// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerActionCall } from "./ComputerActionCall";
import type { CustomToolCall } from "./CustomToolCall";
import type { FunctionCall } from "./FunctionCall";
import type { ShellCall } from "./ShellCall";
import type { TextEditorCall } from "./TextEditorCall";
import type { ToolSearchCall } from "./ToolSearchCall";

export type ToolCall =
  | ({ type: "function" } & FunctionCall)
  | ({ type: "custom" } & CustomToolCall)
  | ({ type: "computer_use" } & ComputerActionCall)
  | ({ type: "shell" } & ShellCall)
  | ({ type: "text_editor" } & TextEditorCall)
  | ({ type: "tool_search" } & ToolSearchCall);
