// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallId } from "./ToolCallId";
import type { ToolOutcome } from "./ToolOutcome";
import type { ToolResultKind } from "./ToolResultKind";

export type ToolResult = {
  call_id: ToolCallId;
  kind: ToolResultKind;
  outcome: ToolOutcome;
};
