// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputId } from "./OutputId";
import type { ToolExecutionState } from "./ToolExecutionState";

export type ToolExecutionDelta = {
  output_index: number;
  output_id: OutputId;
  state: ToolExecutionState;
};
