// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeExecutionTool } from "./CodeExecutionTool";
import type { ComputerUseTool } from "./ComputerUseTool";
import type { CustomTool } from "./CustomTool";
import type { FileSearchTool } from "./FileSearchTool";
import type { FunctionTool } from "./FunctionTool";
import type { ImageGenerationTool } from "./ImageGenerationTool";
import type { McpTool } from "./McpTool";
import type { MemoryTool } from "./MemoryTool";
import type { ShellTool } from "./ShellTool";
import type { TextEditorTool } from "./TextEditorTool";
import type { ToolSearchTool } from "./ToolSearchTool";
import type { WebFetchTool } from "./WebFetchTool";
import type { WebSearchTool } from "./WebSearchTool";

export type ToolDefinition =
  | ({ type: "function" } & FunctionTool)
  | ({ type: "custom" } & CustomTool)
  | ({ type: "web_search" } & WebSearchTool)
  | ({ type: "web_fetch" } & WebFetchTool)
  | ({ type: "file_search" } & FileSearchTool)
  | ({ type: "computer_use" } & ComputerUseTool)
  | ({ type: "code_execution" } & CodeExecutionTool)
  | ({ type: "shell" } & ShellTool)
  | ({ type: "text_editor" } & TextEditorTool)
  | ({ type: "image_generation" } & ImageGenerationTool)
  | ({ type: "mcp" } & McpTool)
  | ({ type: "memory" } & MemoryTool)
  | ({ type: "tool_search" } & ToolSearchTool);
