// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";
import type { ModelId } from "./ModelId";

export type TranslationRequest = {
  model: ModelId;
  audio: MediaSource;
  prompt: string | null;
  temperature: number | null;
};
