// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioUsage } from "./AudioUsage";
import type { TranscriptSegment } from "./TranscriptSegment";
import type { TranscriptWord } from "./TranscriptWord";

export type Transcription = {
  text: string;
  language: string | null;
  duration_seconds: number | null;
  words: Array<TranscriptWord>;
  segments: Array<TranscriptSegment>;
  usage: AudioUsage | null;
};
