// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptSegment = {
  id: string;
  text: string;
  start_seconds: number;
  end_seconds: number;
  speaker: string | null;
};
