// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiarizationConfig } from "./DiarizationConfig";
import type { MediaSource } from "./MediaSource";
import type { ModelId } from "./ModelId";
import type { TimestampGranularity } from "./TimestampGranularity";
import type { TranscriptionMode } from "./TranscriptionMode";

export type TranscriptionRequest = {
  model: ModelId;
  audio: MediaSource;
  language: string | null;
  prompt: string | null;
  temperature: number | null;
  timestamps: Array<TimestampGranularity>;
  diarization: DiarizationConfig | null;
  mode: TranscriptionMode;
};
