// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

export type Translation = {
  text: string;
  source_language: string | null;
  duration_seconds: number | null;
  segments: Array<TranscriptSegment>;
};
