// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationFailure } from "./OperationFailure";
import type { TranscriptSegment } from "./TranscriptSegment";
import type { Transcription } from "./Transcription";

export type TranscriptionEvent =
  | { type: "started" }
  | { type: "text_delta"; text: string }
  | ({ type: "segment" } & TranscriptSegment)
  | ({ type: "finished" } & Transcription)
  | ({ type: "failed" } & OperationFailure);
