// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationFailure } from "./OperationFailure";
import type { VideoJobStatus } from "./VideoJobStatus";

export type VideoJob = {
  id: string;
  status: VideoJobStatus;
  progress: number | null;
  model: string | null;
  error: OperationFailure | null;
  /**
   * 完成后用于 DownloadContent 的标识
   * (OpenAI:video id;Gemini:Veo 文件 id)。未完成或不可下载时为 None。
   */
  content_ref: string | null;
};
