// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 视频轮询 / 下载的入参。
 */
export type VideoJobInput = { channel_id: number; id: string; name: string };
