// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateVideoRequest } from "./CreateVideoRequest";
import type { DeleteVideoRequest } from "./DeleteVideoRequest";
import type { DownloadVideoContentRequest } from "./DownloadVideoContentRequest";
import type { ListVideosRequest } from "./ListVideosRequest";
import type { RetrieveVideoRequest } from "./RetrieveVideoRequest";

export type VideoRequest =
  | ({ type: "create" } & CreateVideoRequest)
  | ({ type: "retrieve" } & RetrieveVideoRequest)
  | ({ type: "list" } & ListVideosRequest)
  | ({ type: "delete" } & DeleteVideoRequest)
  | ({ type: "download_content" } & DownloadVideoContentRequest);
