// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoContent } from "./VideoContent";
import type { VideoDeleted } from "./VideoDeleted";
import type { VideoJob } from "./VideoJob";
import type { VideoJobList } from "./VideoJobList";

export type VideoResponse =
  | ({ type: "job" } & VideoJob)
  | ({ type: "jobs" } & VideoJobList)
  | ({ type: "deleted" } & VideoDeleted)
  | ({ type: "content" } & VideoContent);
