// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoJob } from "./VideoJob";

export type VideoJobList = { jobs: Array<VideoJob>; cursor: string | null };
