// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebFetchTool = {
  allowed_domains: Array<string>;
  blocked_domains: Array<string>;
  max_uses: number | null;
};
