// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { SearchLocation } from "./SearchLocation";

export type WebSearchRequest = {
  model: ModelId | null;
  query: string;
  max_results: number | null;
  allowed_domains: Array<string>;
  blocked_domains: Array<string>;
  location: SearchLocation | null;
};
