// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchContextSize } from "./SearchContextSize";
import type { UserLocation } from "./UserLocation";

export type WebSearchTool = {
  search_context_size: SearchContextSize | null;
  user_location: UserLocation | null;
  allowed_domains: Array<string>;
  blocked_domains: Array<string>;
  max_uses: number | null;
};
