// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldBookV1 } from "./WorldBookV1";

export type WorldBookDefinition = { version: "V1" } & WorldBookV1;
