// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryPosition } from "./EntryPosition";
import type { InjectionRole } from "./InjectionRole";
import type { SelectiveLogic } from "./SelectiveLogic";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 单条世界书条目——也是内容寻址的可编辑单元(HashEdit 的锚点)。
 */
export type WorldBookEntry = {
  name: string;
  content: string;
  keys: Array<string>;
  secondary_keys: Array<string>;
  selective_logic: SelectiveLogic;
  enabled: boolean;
  /**
   * 常驻激活,不参与关键词匹配。
   */
  constant: boolean;
  /**
   * 插入顺序;越小越靠前。
   */
  order: number;
  position: EntryPosition;
  /**
   * `position = at_depth` 时的深度与角色。
   */
  depth: number | null;
  role: InjectionRole | null;
  /**
   * 激活概率百分比(0-100);None 表示必然激活。
   */
  probability: number | null;
  case_sensitive: boolean;
  match_whole_words: boolean;
  /**
   * 递归控制:不被递归扫描触发 / 自身不触发递归 / 延迟到第 N 轮递归。
   */
  exclude_recursion: boolean;
  prevent_recursion: boolean;
  delay_until_recursion: number | null;
  /**
   * 不计入预算上限。
   */
  ignore_budget: boolean;
  extra: { [key in string]: JsonValue };
};
