// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldBookEntry } from "./WorldBookEntry";
import type { JsonValue } from "./serde_json/JsonValue";

export type WorldBookV1 = {
  name: string;
  description: string;
  /**
   * 扫描聊天历史的深度上限;None 表示用运行配置缺省。
   */
  scan_depth: number | null;
  token_budget: number | null;
  recursive_scanning: boolean;
  entries: Array<WorldBookEntry>;
  extra: { [key in string]: JsonValue };
};
